# vCenter Login Information
vcenter_hostname: ''
vcenter_username: ''
vcenter_password: ''

# Variable entries for Linux virtual machine
vsphere_datacenter: ''
resource_pool: ''

# VM Network Components
Mgmt_network: ''
Mgmt_network_nmv4: '255.255.255.0'
Mgmt_network_gwv4: ''

# Tempalate of CentOS 7.9 Linux Server
lin_temp: 'CentOS-7.9-temp'
wdc_vm_name: '{{ lin_temp }}'

# Timezone and NTP Server
# Use below command on a linux system to get timezone:
## timedatectl list-timezones
timezone: 'Etc/UTC'
ntp_server:
  - ''
  - ''

# DNS server details
dns_server1: ''
dns_server2: ''
dns_domain: ''

# Kubernetes Specific Parameters
pod_network: '172.16.0.0/16'   
k8s_master_ip: ''   
