---
- name: Load br_netfilter module
  command: modprobe br_netfilter

- name: Add the br_netfilter module to work across reboot
  shell: |
    echo br_netfilter > /etc/modules-load.d/br_netfilter.conf  

- name: Load the bridge-nf-call-iptables module
  sysctl:
    name: net.bridge.bridge-nf-call-iptables  
    value: '1'
    sysctl_set: yes  
    state: present
    reload: yes  

- name: Configure the yum repo for kubernetes
  copy:
    src: "{{ role_path }}/files/kubernetes.repo"
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: '0644'

- name: Install Kubernetes binaries
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubelet-1.23.7
    - kubeadm-1.23.7
    - kubectl-1.23.7
    - docker  

- name: Start and enable the docker service
  systemd:
    name: docker
    state: restarted
    enabled: yes  

- name: Enable the kubelet service
  systemd:
    name: kubelet
    enabled: yes  

- name: Initialize the kubernetes cluster
  command: kubeadm init --apiserver-advertise-address="{{ k8s_master_ip }}" --apiserver-cert-extra-sans="{{ k8s_master_ip }}"  --node-name k8s-master --pod-network-cidr="{{ pod_network }}"  
      
- name: Generate the kubernetes cluster access
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config     

- name: Install Network Add-on for CNI
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

- name: Get the token for joining the worker nodes
  shell: kubeadm token create  --print-join-command
  register: node_join_command

- debug:
    msg: "{{ node_join_command.stdout }}"

- name: Copy join command to ansible server
  local_action: copy content="{{ node_join_command.stdout_lines[0] }}" dest="/tmp/node_join_command" mode=0755
